
camunda.bpm.admin-user:
  id: cormacarena
  password: 12345

camunda:
  bpm:
    plugin:
      connect:
        enabled: true

logging:
  level:
    com.example.cormacarena: DEBUG

DB_URL: jdbc:mysql://localhost:3306/cormacarena
DB_USER: root
DB_PASSWORD: admin
